import type { Metadata } from "next";

import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Social App",
  description: "Generated by AMA",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          <main className="max-w-7xl mx-auto">
            <NavBar />
            {children}
          </main>
        </NextUIProvider>
      </body>
    </html>
  );
}
